# Bump!

name: CI

on:
  push:
  pull_request:
  check_run:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-toolchain@v0
      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-wasi, cargo-nextest
          cache: false
      - run: |
          cd plugins;
          cargo wasi build -p proto_wasm_test --timings;
      - if: ${{ runner.os == 'Windows' }}
        run: node .github/actions/delete-target-files.js;
        # Windows runs out of disk space
      - run: cargo nextest run --workspace --exclude proto_pdk --profile ci --config-file ./.cargo/nextest.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROTO_DEBUG_COMMAND: 1
          RUST_BACKTRACE: 1
          WASMTIME_BACKTRACE_DETAILS: 1
      - uses: actions/upload-artifact@v3
        with:
          name: perf
          path: |
            target/cargo-timings
      - run: cargo run -- install node
        env:
          PROTO_HOME: "/tmp/proto_test"
      - uses: actions/upload-artifact@v3
        with:
          name: nodebins-${{ runner.os }}
          path: |
            /tmp/proto_test/bin/*
            /tmp/proto_test/shims/*
