# Bump!

name: CI

on:
  push:
  pull_request:
  check_run:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-toolchain@v0
      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-wasi, cargo-nextest
          cache: false
      - run: |
          cd plugins;
          cargo wasi build -p proto_wasm_test --timings;
      - if: ${{ runner.os == 'Windows' }}
        run: node .github/actions/delete-target-files.js;
        # Windows runs out of disk space
      - run: |
          cargo run -- install node
          cargo run -- run npm -- --version
        env:
          PROTO_HOME: "/tmp/proto_test"
          PROTO_LOG: debug
          PROTO_DEBUG_COMMAND: 1
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: proto_home-${{ runner.os }}
          path: |
            /tmp/proto_test/*
