# Bump!

name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-toolchain@v0
      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-wasi, cargo-nextest, just
          cache-base: "^(master|develop-)"
      - if: ${{ runner.os != 'Windows' }}
        run: just build-wasm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Windows runs out of disk space
      - if: ${{ runner.os == 'Windows' }}
        run: |
          just build-wasm;
          node .github/actions/delete-target-files.js;
      - run:  cargo test run --workspace --exclude proto_pdk --no-fail-fast
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROTO_DEBUG_COMMAND: 1
          RUST_BACKTRACE: 1
          WASMTIME_BACKTRACE_DETAILS: 1
